# Generated by Django 3.1.2 on 2020-11-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201118_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Rut_usuario',
            field=models.TextField(default='G', max_length=10),
        ),
    ]
