# Generated by Django 3.1.2 on 2020-11-28 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201119_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Rut_usuario',
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='user',
            name='rut_usuario',
            field=models.TextField(default='G', max_length=10),
        ),
    ]
