# Generated by Django 2.2.3 on 2020-10-22 06:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cant_adultos',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='cart',
            name='cant_ninios',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='cart',
            name='cantidad_de_dias',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='cart',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 22, 3, 21, 37, 923104)),
        ),
        migrations.AddField(
            model_name='cart',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 22, 3, 21, 37, 923104)),
        ),
        migrations.AddField(
            model_name='cart',
            name='pagado',
            field=models.BinaryField(default=0),
        ),
    ]
