# Generated by Django 2.2.3 on 2020-10-22 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20201022_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 22, 3, 28, 5, 366277)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 22, 3, 28, 5, 366277)),
        ),
    ]
