# Generated by Django 2.2.3 on 2020-10-22 06:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20201022_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 22, 3, 29, 21, 290981)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 22, 3, 29, 21, 291980)),
        ),
        migrations.CreateModel(
            name='Check_Out',
            fields=[
                ('id_check_out', models.AutoField(primary_key=True, serialize=False)),
                ('desc_danios', models.TextField()),
                ('monto_danios', models.BigIntegerField()),
                ('pagado', models.BinaryField()),
                ('firmado', models.BinaryField()),
                ('a_id_arriendo', models.ForeignKey(db_column='a_id_arriendo', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='carts.Cart')),
            ],
            options={
                'db_table': 'Check_Out',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Check_In',
            fields=[
                ('id_check_in', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_check_in', models.TextField()),
                ('firmado', models.BinaryField()),
                ('a_id_arriendo', models.ForeignKey(db_column='a_id_arriendo', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='carts.Cart')),
            ],
            options={
                'db_table': 'Check_In',
                'managed': True,
            },
        ),
    ]
