# Generated by Django 2.2.3 on 2020-10-22 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20201022_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 22, 3, 33, 11, 936184)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='fecha_termino',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 22, 3, 33, 11, 936184)),
        ),
    ]
