# Generated by Django 2.2.3 on 2020-10-23 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20201022_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='fecha_inicio',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 10, 23, 18, 5, 9, 696879)),
        ),
        migrations.AlterField(
            model_name='cart',
            name='fecha_termino',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 10, 23, 18, 5, 9, 696879)),
        ),
    ]
