# Generated by Django 2.2.3 on 2020-10-23 21:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0012_auto_20201023_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta_Credito',
            fields=[
                ('codigo', models.IntegerField()),
                ('numero_tarjeta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('compania', models.TextField()),
                ('mes_exp', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(13)])),
                ('anio_exp', models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100)])),
                ('u_id_cliente', models.ForeignKey(db_column='u_id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Tarjeta_Credito',
                'managed': True,
            },
        ),
    ]
