# Generated by Django 2.2.3 on 2020-10-23 21:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carts', '0013_tarjeta_credito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id_tour', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_tour', models.TextField()),
                ('numero_vacantes', models.IntegerField(validators=[django.core.validators.MaxValueValidator(501)])),
                ('precio', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(1000000)])),
            ],
            options={
                'db_table': 'Tour',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_transporte', models.AutoField(primary_key=True, serialize=False)),
                ('vehiculo', models.TextField()),
                ('destino', models.TextField()),
                ('origen', models.TextField()),
                ('precio', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000000)])),
                ('u_id_funcionario', models.ForeignKey(db_column='u_id_funcionario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Transporte',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicios_Extra',
            fields=[
                ('id_servicio_extra', models.AutoField(primary_key=True, serialize=False)),
                ('monto_servicio', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000000)])),
                ('desc_servicio', models.TextField()),
                ('estado_servicio', models.TextField()),
                ('fecha_servicio', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('horario_servicio', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('a_id_arriendo', models.ForeignKey(db_column='a_id_arriendo', on_delete=django.db.models.deletion.DO_NOTHING, to='carts.Cart')),
                ('t_id_tour', models.ForeignKey(blank=True, db_column='t_id_tour', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carts.Tour')),
                ('t_id_transporte', models.ForeignKey(blank=True, db_column='t_id_transporte', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carts.Transporte')),
            ],
            options={
                'db_table': 'Servicios_Extra',
                'managed': True,
            },
        ),
    ]
