# Generated by Django 3.1.2 on 2020-11-18 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201118_1854'),
        ('carts', '0014_servicios_extra_tour_transporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='Tarjeta_Credito',
            name='u_id_cliente',
            field=models.ForeignKey(db_column='u_id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='Transporte',
            name='u_id_funcionario',
            field=models.ForeignKey(db_column='u_id_funcionario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
