# Generated by Django 3.1.2 on 2020-11-28 22:09

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0015_auto_20201118_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='cant_adultos',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AddField(
            model_name='cartproducts',
            name='cant_ninios',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='cartproducts',
            name='fecha_inicio',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cartproducts',
            name='fecha_termino',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
