# Generated by Django 3.1.2 on 2020-11-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0016_auto_20201128_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=5),
        ),
    ]
