# Generated by Django 3.1.2 on 2020-11-30 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0019_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios_extra',
            name='a_id_arriendo',
        ),
        migrations.AddField(
            model_name='servicios_extra',
            name='a_id_cartproduct',
            field=models.ForeignKey(db_column='a_id_cartproduct', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carts.cartproducts'),
        ),
    ]
