# Generated by Django 3.1.2 on 2020-11-30 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0022_remove_servicios_extra_t_id_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios_extra',
            name='t_id_cart',
            field=models.ForeignKey(blank=True, db_column='t_id_cart', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='carts.cart'),
        ),
    ]
