# Generated by Django 3.1.2 on 2020-11-30 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0023_servicios_extra_t_id_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='subtotal',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
    ]
