# Generated by Django 3.1.2 on 2020-12-08 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0024_auto_20201130_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tour',
            name='hora_termino',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
