# Generated by Django 3.1.2 on 2020-12-08 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0025_auto_20201208_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='fecha_tour',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
