# Generated by Django 2.2.3 on 2020-10-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Departamento',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('descricion_estado', models.TextField()),
            ],
            options={
                'db_table': 'Estado_Departamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipo_Departamento',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'Tipo_Departamento',
                'managed': True,
            },
        ),
    ]
