# Generated by Django 2.2.3 on 2020-10-16 17:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_estado_departamento_tipo_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cantidad_de_baños',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='product',
            name='cantidad_de_camas',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='product',
            name='cantidad_de_dormitorios',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='product',
            name='cantidad_de_muebles',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='product',
            name='cantidad_de_televisores',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='product',
            name='e_id_estado',
            field=models.ForeignKey(db_column='e_id_estado', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Estado_Departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='t_id_tipo',
            field=models.ForeignKey(db_column='t_id_tipo', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Tipo_Departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='tamaño_de_departamento',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
    ]
