# Generated by Django 2.2.3 on 2020-10-16 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201016_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cantidad_de_baños',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='cantidad_de_camas',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='cantidad_de_dormitorios',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='cantidad_de_muebles',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='cantidad_de_televisores',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='tamaño_de_departamento',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50)]),
        ),
    ]
