# Generated by Django 2.2.3 on 2020-10-22 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20201016_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'ciudad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.TextField()),
                ('c_id_ciudad', models.ForeignKey(db_column='c_id_ciudad', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Ciudad')),
            ],
            options={
                'db_table': 'Comuna',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'Region',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('direccion', models.TextField()),
                ('ndepartamentos_disponibles', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('nombre', models.TextField()),
                ('c_id_comuna', models.ForeignKey(db_column='c_id_comuna', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Comuna')),
            ],
            options={
                'db_table': 'Empresa',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='r_id_region',
            field=models.ForeignKey(db_column='r_id_region', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Region'),
        ),
    ]
