# Generated by Django 2.2.3 on 2020-10-22 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201022_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id_mantencion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.TextField()),
                ('fecha_termino', models.TextField()),
                ('descripcion_mantencion', models.TextField()),
                ('d_numero_de_departamento', models.ForeignKey(db_column='d_numero_de_departamento', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Product')),
            ],
            options={
                'db_table': 'Mantencion',
                'managed': True,
            },
        ),
    ]
