# Generated by Django 2.2.3 on 2020-10-23 21:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_mantencion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Inventario',
            fields=[
                ('descripcion', models.TextField()),
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Tipo_Inventario',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='mantencion',
            name='fecha_inicio',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 10, 23, 18, 5, 9, 681258)),
        ),
        migrations.AlterField(
            model_name='mantencion',
            name='fecha_termino',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 10, 23, 18, 5, 9, 681258)),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('marca', models.TextField()),
                ('fecha_compra', models.DateField(blank=True, default=datetime.datetime(2020, 10, 23, 18, 5, 9, 696879))),
                ('costo', models.IntegerField()),
                ('d_numero_de_departamento', models.ForeignKey(db_column='d_numero_de_departamento', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Product')),
                ('t_id_tipo', models.ForeignKey(db_column='t_id_tipo', on_delete=django.db.models.deletion.DO_NOTHING, to='products.Tipo_Inventario')),
            ],
            options={
                'db_table': 'Inventario',
                'managed': True,
            },
        ),
    ]
