# Generated by Django 3.1.2 on 2020-11-30 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20201102_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='e_id_empresa',
            field=models.ForeignKey(db_column='e_id_empresa', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='products.empresa'),
        ),
    ]
